spring:
  profiles:
    active:
      - dog
      - EN
      - qa
guru:
  username: YmlUsername
  password: YmlPassword
  jdbcurl: YmlURL

---
spring:
  config:
    activate:
      on-profile: prod
guru:
  username: prodUsername
  password: prodPassword
  jdbcurl: prodURL
